NDEV-1723: Extract filtering module
neonlabsorg/geyser-neon-plugin pull request #16
Opened 2023-06-14 06:53 UTC by andreisilviudragnea

2023-06-21 06:37 UTC, Deniskore requested changes
I think you should print the changes in the filter config to the log file like it was before, otherwise it is not clear what exactly was replaced in the file.
You can simplify diff if you want.

2023-06-21 06:37 UTC, Deniskore commented on geyser_neon/src/filter/real_filter/filter_config_hot_reload.rs
> +            let (_, current_filter_config) = &*self.current_filter_config.read().unwrap();
Please handle this Result without unwrap()

2023-06-21 06:37 UTC, Deniskore commented on geyser_neon/src/filter/real_filter/filter_config_hot_reload.rs
> +        *self.current_filter_config.write().unwrap() = (
Please handle this Result without unwrap()

2023-06-21 16:13 UTC, andreisilviudragnea commented on geyser_neon/src/filter/real_filter/filter_config_hot_reload.rs
> +            let (_, current_filter_config) = &*self.current_filter_config.read().unwrap();
This `.unwrap()` and the next one fail if the `RwLock` gets [`poisoned`](https://doc.rust-lang.org/nomicon/poisoning.html), but this does should never happen in this implementation.

Using `?` is not possible because `RwLockReadGuard` is `!Send`, but `Send` is required by `anyhow::Error`.

2023-06-21 16:14 UTC, andreisilviudragnea commented on geyser_neon/src/filter/real_filter/filter_config_hot_reload.rs
> +        *self.current_filter_config.write().unwrap() = (
The same comment as above.

2023-06-22 05:26 UTC, Deniskore approved these changes

2023-06-23 10:02 UTC, dk-neon approved these changes
LGTM

2023-06-23 10:56 UTC, merged